//
//  GenreAPIWorker.swift
//  Moviepedia
//
//  Created by Lucas Ferraço on 29/08/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

class GenreAPIWorker: TMDbClient {
	
	private let networkDecodableWorker = NetworkWorker()
	private var movieList: [Genre]? = nil
	private var tvList: [Genre]? = nil
	
	public enum Kind: String {
		case movie	= "/movie"
		case tv		= "/tv"
	}
	
	private struct GenreListResponse: Decodable {
		let genres: [Genre]
	}
	
	public struct Genre: Decodable {
		let id: Int
		let name: String
	}
	
	//MARK: Singleton Definition
	private static var theOnlyInstance: GenreAPIWorker?
	public static var shared: GenreAPIWorker {
		get {
			if theOnlyInstance == nil {
				theOnlyInstance = GenreAPIWorker()
			}
			return theOnlyInstance!
		}
	}
	private override init() {}
	
	//MARK:- Public Methods
	
	/// Downloads a list of genres according to the specified kind.
	///
	/// - Parameters:
	///   - kind: Whether tv or movie genres.
	///   - completion: The handler to be called once the request has finished.
	public func fetchGenres(of kind: Kind, _ completion: (([Genre]?) -> Void)? = nil) {
		if let list = checkForDownloadedList(of: kind) {
			completion?(list)
		}
		
		let completeURL = url(for: .genre) + kind.rawValue + "/list"
		let params = parameters([.languageCode])
		
		networkDecodableWorker.get(from: completeURL, with: params) { (genreList: GenreListResponse?, error) in
			guard let list = genreList else {
				completion?(nil)
				return
			}
			
			self.storeDownloaded(list: list.genres, of: kind)
			completion?(list.genres)
		}
	}
	
	//MARK:- Auxiliary Methods
	
	private func checkForDownloadedList(of kind: Kind) -> [Genre]? {
		switch kind {
		case .movie:
			return movieList
		case .tv:
			return tvList
		}
	}
	
	private func storeDownloaded(list: [Genre], of kind: Kind) {
		switch kind {
		case .movie:
			movieList = list
		case .tv:
			tvList = list
		}
	}
	
}
