//
//  ImageDownloadWorker.swift
//  Moviepedia
//
//  Created by Lucas Ferraco on 28/08/18.
//  Copyright © 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ImageDownloadWorker: TMDbClient {
    
    private let networkDecodableWorker = NetworkDecodableWorker()
    
    //MARK: Singleton Definition
    private static var theOnlyInstance: ImageDownloadWorker?
    public static var shared: ImageDownloadWorker {
        get {
            if theOnlyInstance == nil {
                theOnlyInstance = ImageDownloadWorker()
            }
            return theOnlyInstance!
        }
    }
    private override init() {
        super.init()
        updateProperties()
    }
    
    //MARK:- Shared Methods
    
    //MARK:- Auxiliary Methods
    
    private func updateProperties(_ completion: ((NetworkDecodableWorkerError?) -> Void)? = nil) {
        let propsURL = url(for: .configuration)
        let params = parameters()
        
        networkDecodableWorker.get(from: propsURL, with: params) { (properties: Properties?, error) in
            guard let properties = properties else {
                if let error = error {
                    completion?(error)
                } else {
                    completion?(.Failure)
                }
                
                return
            }
            
            self.properties = properties
            completion?(nil)
        }
    }
}
