//
//  ListMoviesModels.swift
//  Moviepedia
//
//  Created by Lucas Ferraço on 29/08/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListMovies {
	
	//MARK:- List Movies
	
	struct DisplayableMovieInfo {
		var id: Int
		var title: String
		var image: UIImage?
		var genre: String
		var releaseDate: String
	}
	
	enum ListMovies {
		struct Response {
			let movies: [Movie]?
			let genres: [Int : String]?
			let error: MoviesAPIWorkerError?
		}
		
		struct ViewModel {
			let moviesInfo: [DisplayableMovieInfo]?
			let errorMessage: String?
		}
	}
	
	//MARK:- Get Movie Image
	
	enum GetMovieImage {
		struct Request {
			let movieId: Int
		}
		
		struct Response {
			let movieId: Int
			let movieImage: UIImage?
		}
		
		struct ViewModel {
			let movieId: Int
			let movieImage: UIImage
		}
	}
	
	//MARK:- Get More Movies
	
	enum GetMoreMovies {
		struct Response {
			let newMovies: [Movie]?
			let genres: [Int : String]?
			let error: MoviesAPIWorkerError?
		}
	}
}
