//
//  ListMoviesInteractor.swift
//  Moviepedia
//
//  Created by Lucas Ferraço on 29/08/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListMoviesBusinessLogic {
	func getUpcomingMovies()
}

protocol ListMoviesDataStore {
	var movie: Movie? { get set }
}

class ListMoviesInteractor: ListMoviesBusinessLogic, ListMoviesDataStore {
	var presenter: ListMoviesPresentationLogic?
	
	var moviesWorker = MoviesAPIWorker.shared
	var downloadImageWorker = DownloadImageAPIWorker.shared
	private var currentPage = 1
	
	// MARK:- ListMoviesDataStore protocol
	
	var movie: Movie? = nil
	
	// MARK:- ListMoviesBusinessLogic protocol
	
	func getUpcomingMovies() {
		moviesWorker.fetchMoviesList(of: .upcoming, on: currentPage) { (movies, error) in
			let response = ListMovies.ListMovies.Response(movies: movies, error: error)
			self.presenter?.presentMoviesList(with: response)
		}
	}
}
