//
//  ListMoviesRouter.swift
//  Moviepedia
//
//  Created by Lucas Ferraço on 29/08/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListMoviesRoutingLogic {
	func routeMovieDetails()
}

protocol ListMoviesDataPassing {
	var dataStore: ListMoviesDataStore? { get }
}

class ListMoviesRouter: NSObject, ListMoviesRoutingLogic, ListMoviesDataPassing {
	weak var viewController: ListMoviesViewController?
	var dataStore: ListMoviesDataStore?
	
	//MARK:- Routing
	
	func routeMovieDetails() {
		let storyboard = UIStoryboard(name: "MovieDetails", bundle: nil)
		let destinationVC = storyboard.instantiateViewController(withIdentifier: "MovieDetailsViewController") as! MovieDetailsViewController
		var destinationDS = destinationVC.router!.dataStore!
		passDataToMovieDetails(source: dataStore!, destination: &destinationDS)
		navigateToMovieDetails(source: viewController!, destination: destinationVC)
	}
	
	//MARK:- Navigation
	
	func navigateToMovieDetails(source: ListMoviesViewController, destination: MovieDetailsViewController) {
	  source.navigationController?.pushViewController(destination, animated: true)
	}
	
	//MARK:- Passing data
	
	func passDataToMovieDetails(source: ListMoviesDataStore, destination: inout MovieDetailsDataStore) {
	  destination.movie = source.movie
	}
}
