//
//  ListMoviesInteractor.swift
//  Moviepedia
//
//  Created by Lucas Ferraço on 29/08/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListMoviesBusinessLogic {
	func getUpcomingMovies()
	func getMovieImage(with request: ListMovies.GetMovieImage.Request, _ completion: @escaping (UIImage) -> Void)
}

protocol ListMoviesDataStore {
	var movie: Movie? { get set }
}

class ListMoviesInteractor: ListMoviesBusinessLogic, ListMoviesDataStore {
	var presenter: ListMoviesPresentationLogic?
	
	var moviesDictionary: [Int : Movie] = [:]
	var moviesWorker = MoviesAPIWorker.shared
	private var currentPage = 1
	
	var downloadImageWorker = DownloadImageAPIWorker.shared
	
	// MARK:- ListMoviesDataStore protocol
	
	var movie: Movie? = nil
	
	// MARK:- ListMoviesBusinessLogic protocol
	
	func getUpcomingMovies() {
		moviesWorker.fetchMoviesList(of: .upcoming, on: currentPage) { (movies, error) in
			if let movies = movies {
				self.store(movies: movies)
			}
			
			let response = ListMovies.ListMovies.Response(movies: movies, error: error)
			self.presenter?.presentMoviesList(with: response)
		}
	}
	
	func getMovieImage(with request: ListMovies.GetMovieImage.Request, _ completion: @escaping (UIImage) -> Void) {
		let chosenMovie = moviesDictionary[request.movieId]
		
		if let posterImage = chosenMovie?.posterImage {
			present(image: posterImage, id: request.movieId, completion)
			return
		} else if let backdropImage = chosenMovie?.backdropImage {
			present(image: backdropImage, id: request.movieId, completion)
			return
		}
		
		let (path, imageType) = getImagePath(for: chosenMovie)
		
		guard !path.isEmpty else {
			self.present(image: nil, id: request.movieId, completion)
			return
		}
		
		downloadImageWorker.downloadImage(from: path, type: imageType) { (callbackPath, image) in
			switch imageType {
			case .poster:
				chosenMovie?.posterImage = image
			case .backdrop:
				chosenMovie?.backdropImage = image
			}
			
			if callbackPath == path { // Avoid the image to load on the wrong spot
				self.present(image: image, id: request.movieId, completion)
			}
		}
	}
	
	//MARK:- Auxiliary Methods
	
	private func store(movies: [Movie]) {
		for i in 0..<movies.count {
			let currentMovie = movies[i]
			
			if let id = currentMovie.id {
				self.moviesDictionary.updateValue(currentMovie, forKey: id)
			} else {
				self.moviesDictionary.updateValue(currentMovie, forKey: i)
			}
		}
	}
	
	private func present(image: UIImage?, id: Int, _ completion: @escaping (UIImage) -> Void) {
		let response = ListMovies.GetMovieImage.Response(movieId: id, movieImage: image)
		self.presenter?.presentMovieImage(with: response, completion)
	}
	
	private func getImagePath(for movie: Movie?) -> (path: String, type: DownloadImageAPIWorker.ImageType) {
		var path = ""
		var imageType: DownloadImageAPIWorker.ImageType = .poster
		if let posterPath = movie?.posterPath {
			path = posterPath
		} else if let backdropPath = movie?.backdropPath {
			path = backdropPath
			imageType = .backdrop
		}
		
		return (path, imageType)
	}
}
