//
//  MovieDetailsInteractor.swift
//  Moviepedia
//
//  Created by Lucas Ferraço on 30/08/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailsBusinessLogic {
	func doSomething(request: MovieDetails.Something.Request)
}

protocol MovieDetailsDataStore {
	//var name: String { get set }
}

class MovieDetailsInteractor: MovieDetailsBusinessLogic, MovieDetailsDataStore {
	var presenter: MovieDetailsPresentationLogic?
	var worker: MovieDetailsWorker?
	//var name: String = ""
	
	// MARK: Do something
	
	func doSomething(request: MovieDetails.Something.Request) {
		worker = MovieDetailsWorker()
		worker?.doSomeWork()
		
		let response = MovieDetails.Something.Response()
		presenter?.presentSomething(response: response)
	}
}
