//
//  MovieDetailsViewController.swift
//  Moviepedia
//
//  Created by Lucas Ferraço on 30/08/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailsDisplayLogic: class {
	func displayMovieInfo(with viewModel: MovieDetails.ShowMovieDetails.ViewModel)
}

class MovieDetailsViewController: UIViewController, MovieDetailsDisplayLogic {
	var interactor: MovieDetailsBusinessLogic?
	var router: (NSObjectProtocol & MovieDetailsRoutingLogic & MovieDetailsDataPassing)?
	
	@IBOutlet weak var backgroundImageView: UIImageView!
	@IBOutlet weak var titleLabel: UILabel!
	@IBOutlet weak var releaseDateLabel: UILabel!
	@IBOutlet weak var genresLabel: UILabel!
	@IBOutlet weak var overviewLabel: UILabel!
	
	
	//MARK:- Object lifecycle
	
	override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
		super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
		setup()
	}
	
	required init?(coder aDecoder: NSCoder) {
		super.init(coder: aDecoder)
		setup()
	}
	
	//MARK:- Setup
	
	private func setup() {
		let viewController = self
		let interactor = MovieDetailsInteractor()
		let presenter = MovieDetailsPresenter()
		let router = MovieDetailsRouter()
		viewController.interactor = interactor
		viewController.router = router
		interactor.presenter = presenter
		presenter.viewController = viewController
		router.viewController = viewController
		router.dataStore = interactor
	}
	
	//MARK:- View lifecycle
	
	override func viewDidLoad() {
		super.viewDidLoad()
		interactor?.getMovieDetails()
	}
	
	//MARK:- MovieDetailsDisplayLogic
	
	func displayMovieInfo(with viewModel: MovieDetails.ShowMovieDetails.ViewModel) {
		
		navigationController?.title = viewModel.movieInfo.title
		
		titleLabel.text = viewModel.movieInfo.title
		releaseDateLabel.text = viewModel.movieInfo.releaseDate
		genresLabel.text = viewModel.movieInfo.genres
		overviewLabel.text = viewModel.movieInfo.overview
		
		backgroundImageView.image = viewModel.backgroundImage
	}
}
