//
//  MovieDetailsPresenter.swift
//  Moviepedia
//
//  Created by Lucas Ferraço on 30/08/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailsPresentationLogic {
	func presentSomething(response: MovieDetails.Something.Response)
}

class MovieDetailsPresenter: MovieDetailsPresentationLogic {
	weak var viewController: MovieDetailsDisplayLogic?
	
	// MARK: Do something
	
	func presentSomething(response: MovieDetails.Something.Response) {
		let viewModel = MovieDetails.Something.ViewModel()
		viewController?.displaySomething(viewModel: viewModel)
	}
}
