//
//  MovieDetailsModels.swift
//  Moviepedia
//
//  Created by Lucas Ferraço on 30/08/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MovieDetails {
	
	struct MovieInfo {
		let title: String?
		let releaseDate: String?
		let genres: String?
		let overview: String?
	}
	
	// MARK: Show Movie Details
	
	enum ShowMovieDetails {
		struct Response {
			let movie: Movie
			let genres: [Int : String]?
			let backgroundImage: UIImage?
		}
		
		struct ViewModel {
			let movieInfo: MovieInfo
			let backgroundImage: UIImage?
		}
	}
}
