//
//  MovieDetailsInteractor.swift
//  Moviepedia
//
//  Created by Lucas Ferraço on 30/08/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailsBusinessLogic {
	func getMovieDetails()
}

protocol MovieDetailsDataStore {
	var movie: Movie! { get set }
}

class MovieDetailsInteractor: MovieDetailsBusinessLogic, MovieDetailsDataStore {
	var presenter: MovieDetailsPresentationLogic?
	
	var genreWorker = GenreAPIWorker.shared
	
	//MARK- MovieDetailsDataStore
	
	var movie: Movie!
	
	// MARK:- MovieDetailsBusinessLogic
	
	func getMovieDetails() {
		self.genreWorker.fetchGenres(of: .movie) { (genreList) in
			var genreDict: [Int : String]? = [:]
			
			if let genreList = genreList {
				for genre in genreList {
					genreDict?.updateValue(genre.name, forKey: genre.id)
				}
			} else {
				genreDict = nil
			}
			
			var background: UIImage?
			if let posterImage = self.movie.posterImage {
				background = posterImage
			} else if let backdropImage = self.movie.backdropImage {
				background = backdropImage
			}
			
			let response = MovieDetails.ShowMovieDetails.Response(movie: self.movie, genres: genreDict, backgroundImage: background)
			self.presenter?.presentMovieDetails(with: response)
		}
	}
}
